dist: bionic
sudo: required
language: c

branches:
  only:
  - lablgtk3

cache:
  apt: true
  directories:
  - $HOME/.opam

addons:
  apt:
    packages:
    - valac
    - meson                     # until libgtksourceview-4-dev arrives
    - libgtksourceview-3.0-dev
    - libgtkspell3-3-dev

env:
  global:
  - OPAMJOBS="2"
  - OPAMROOTISOK="true"
  - OPAMYES="true"
  - COMPILER="4.07.1"
  - BASE_OPAM="camlp5 dune cairo2 ocamlfind"

  # Main test suite, some examples don't work in 4.05.0
  matrix:
  - TEST_TARGET="build"       COMPILER="4.05.0"
  - TEST_TARGET="build-all"   COMPILER="4.06.1"
  - TEST_TARGET="build-all"   COMPILER="4.07.1"
  - TEST_TARGET="build-all"   COMPILER="4.08.0"
  - TEST_TARGET="build-all"   COMPILER="4.09.0"
  - TEST_TARGET="nopromote"   COMPILER="4.10.0+trunk" BASE_OPAM="dune cairo2 ocamlfind"
  - TEST_TARGET="opam"        COMPILER="4.07.1"
  - TEST_TARGET="opam"        COMPILER="4.08.0"
  - TEST_TARGET="opam"        COMPILER="4.09.0"

matrix:
  include:
    - os: osx
      env:
        - TEST_TARGET="build" COMPILER="4.07.1"
        - PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
      cache:
        ccache: true
        directories:
          - $HOME/.opam
          - $HOME/Library/Caches/Homebrew
      before_cache:
        - brew cleanup
      before_install: |
        set -e
        brew update
        brew upgrade wget
        brew unlink python@2
        brew install curl ccache opam pkg-config gtk+3 gtksourceview3 gtksourceview4 gtkspell3

before_install: |
  curl -sL https://download.gnome.org/sources/gtksourceview/4.2/gtksourceview-4.2.0.tar.xz | tar xvJ
  pushd gtksourceview-4.2.0 && ./configure && make && sudo make install
  # pushd gtksourceview-4.2.0 && mkdir build && meson build && (cd build && ninja && sudo ninja install)
  popd
  sudo curl -sL https://github.com/ocaml/opam/releases/download/2.0.6/opam-2.0.6-x86_64-linux -o /usr/bin/opam
  sudo chmod 755 /usr/bin/opam

install: |
  opam init --bare --disable-sandboxing
  opam repo add -a beta https://github.com/ocaml/ocaml-beta-repository.git
  opam switch create "$COMPILER" --repositories=default,beta || true
  opam switch set "$COMPILER"
  eval $(opam env)
  opam install $BASE_OPAM
  opam list

script:
- set -e
- echo 'Building LablGtk...' && echo -en 'travis_fold:start:lablgtk.build\\r'
- make "$TEST_TARGET"
- echo -en 'travis_fold:end:lablgtk.build\\r'
